language: r

env:
  global:
    - R_PKG="$(basename $TRAVIS_REPO_SLUG)" R_KNITR_OPTIONS="knitr.chunk.tidy=TRUE" PATH=$HOME/bin:$PATH
    - secure: "vuG0rF6O93djR+nMUOFjjQsgED/3ZKbS3xg7v+pk5EiWoNsi9Rz1oowgU8/BwqEl7YHLeA0oDTR+OGdpjjvxj0ZUCMDf0HNC/At74aTwltIsuXXXBN70RVve41BnwFkYUfCq4zs7C7t3sPUXU01faXaXD1PxdIYNoLCHUWXH9TO49VgtJQQHIg4JCRXiw4naefP0Y/gCGR1NH4h0CAQH1/P4Y6x4KJOFuurbV6fZI2sjIGGh1PXywZ9AGAjg4z+JCHROsLdbg5VobGOF8HDP4b8q/c+Bq4Xy1TWovu1L95neaWffTVFJ0XUSWomomCJOkhl9zqAUa+oSY7NNtubdIdoAQH9qpACaCHO4Zi7skz65O/xcNv+2ym2hAtfsTE+y0II8jU3tt4e6T6JIA9tR9Fop5BtjxvU0aud6qm2HjeH3VjV0yPAVm30iPBPbufboeO6JEwFZawrfsSRHvQK5evDXuBsElEBk+4/CW4XHrOJIOjqM5GNatnGEVvxEoy6wRVR7cTvQS7eNJfRDW7UGZZElAZKG1/dZn17aHJ0BPhBiiISt/eZ7/78y4NJysSJqNO69eXloUox1da3MLgapK0+eyDFYyxr5fdIA9SemWXt/1JJ4Ef5feygr6WESVDa2gBnK5FAEWU+CAmi7hB9h4ozZyaAxBbOa11Iu3DrhBPI="

r_github_packages:
  - rstudio/bookdown

install:
  - Rscript -e "if (!require('ggplot2')) install.packages('ggplot2')"
  - Rscript -e "if (!require('devtools')) install.packages('devtools')"


before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh

cache:
  packages: yes

  