language: r

env:
  global:
    - R_PKG="$(basename $TRAVIS_REPO_SLUG)" R_KNITR_OPTIONS="knitr.chunk.tidy=TRUE" PATH=$HOME/bin:$PATH
    - secure: "sVlZaWb0Xy3e+PqVquwNA+932mFub/qNoMjKDPP0+8xBLD1YN2crm3Jq2lvB1/MDoqReK2Fzyz50zyBC2FgFnwN/7hyNkws9HtMTHpEYOn29JOf+tPLONw2WzTT2YTzVpYL4Z+t4g6sAKAtH9Bs9ncslvLhGy1UeEQmUW/uDV3jFTwjJ8mIGKwThrSTINJQYmTeg8ZmiDMG5fujBnAp91f9yAXEoIAPFkzv/pqcytt3PQxmzcpuSYeFO1WKthp9kyGlnOI+mKdIOdTRFDQ0z21JPrWMGmTaD4rZEzBrQiViNaQWZWLOM2BUN25nxWzRdmwiGpg98kYkxHY9WWwpyHjb7yn+8ysvqVqcE1KqdwZCLYLlI7l1SP7g8TeZQHlgPHzIHbi///bgAn02B4C7SmXeKPQkPBTAkbxdlwJygttZFw3exwuqGkmeHkd63rOzJTtphoWLHYICzVcGpYjKJT3mj7qZTioqjTRdzFnwzMT3i+JdaU9AyATl2L8079WM6D1tjIIP68QFDGMq6FpCksdw4jkp0C5IrThPopYawLCWBMGNdMyjh+XDLl9noDZaMR+URgbgYXBGSInCupp+3PqQGITPnVdk1PRdRBFtZ3YGjsccQ0eOOz1txrlSTTc1pRv0sxcIvAqpZ//cxvLsh9odtl9Nlf5tA/H3Ct/2lMRg="

r_github_packages:
  - rstudio/bookdown

install:
  - Rscript -e "if (!require('ggplot2')) install.packages('ggplot2')"
  - Rscript -e "if (!require('devtools')) install.packages('devtools')"


before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

after_script:
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GH_TOKEN}:@github.com" > .git/credentials

script:
  - ./_build.sh
  - ./_deploy.sh

cache:
  packages: yes

  